Harry fiftyfifty - updated ToggleButtonGroups into standalone components
mdnrosen/sillyWC23 pull request #7
Opened 2023-09-07 20:25 UTC by hphilpotts

PR heading says it all.

One query re. whether to import `useGuesses()` into both parent `FiftyFiftyRound` and respective child `ToggleGroup` components, or to just do this in the parent and pass guesses down as a prop...or something. Long day.

2023-09-07 20:28 UTC, mdnrosen commented on src/components/ToggleGroup.jsx
> +    const { guesses } = useGuesses() // ? pass as prop from parent [also has useGuesses()] instead?
In this case its better to useContext as we're already passing quite a few props. Plus the whole point of our context here is to minimise passing the same props all the time

2023-09-07 20:34 UTC, mdnrosen requested changes

2023-09-07 20:34 UTC, mdnrosen commented on src/components/ToggleGroup.jsx
> +            <ToggleButton name={name} value={value1} aria-label={buttonLabel1}>{value1}</ToggleButton>
You have 3 buttons so I would use an array, then you can map over it. Pass the array of 'options' as props then use the index to pick out the data you need

2023-09-07 20:34 UTC, mdnrosen commented on src/pages/FiftyFiftyRound.jsx
> +                                        values={{ name: "h2h_superover", value1: "true", value2: "false" }}
I think (as above) you can build an array for this data

const options = [{
   label: 'Pakistan',
   value: 'pakistan'
   ariaText: 'some text here'
}}
<ToggleGroup
     options={options} />

2023-09-07 20:35 UTC, mdnrosen commented on src/pages/FiftyFiftyRound.jsx
> +                                        values={{ name: "h2h_superover", value1: "true", value2: "false" }}
then pass that as props

2023-09-08 09:59 UTC, hphilpotts commented
Reckon this should be good to go. 

Props for TG component passed as:

```
<ToggleGroup
  name=string // provides the key for guesses context
  values=[string1, string2, *string3] // provides the value for guesses context, TButton text, rendered using .map()
  labels=[string1, string2, string3, string4] // provides aria-labels for TBGroup, TButtons 1, 2 and (optional) 3
  handleChange=function // ...
/>
```

Redundant imports, comments and `console.log` statements cleaned out.

2023-09-09 11:46 UTC, mdnrosen approved these changes

2023-09-09 11:46 UTC, merged